#!/bin/sh

# name: ...
# comment: ...
# uid: ...
# gid: ...
# password: ...
# shell: ...
# class: ...

echo "$0"

NAME=`grep '^name:' $PINSPOT_ACTION_FILE | sed 's/^[^:]*:\(.*\)/\1/' | sed 's/^ //'`
if test -z "$NAME"; then
    echo "error: name missing"
    exit 1
fi
COMMENT="`grep '^comment:' $PINSPOT_ACTION_FILE | sed 's/^[^:]*:\(.*\)/\1/' | sed 's/^ //'`"
GID=`grep '^gid:' $PINSPOT_ACTION_FILE | sed 's/^[^:]*:\(.*\)/\1/' | sed 's/^ //'`
UID=`grep '^uid:' $PINSPOT_ACTION_FILE | sed 's/^[^:]*:\(.*\)/\1/' | sed 's/^ //'`
PASSWORD=`grep '^password:' $PINSPOT_ACTION_FILE | sed 's/^[^:]*:\(.*\)/\1/' | sed 's/^ //'`
SHELL=`grep '^shell:' $PINSPOT_ACTION_FILE | sed 's/^[^:]*:\(.*\)/\1/' | sed 's/^ //'`
CLASS=`grep '^class:' $PINSPOT_ACTION_FILE | sed 's/^[^:]*:\(.*\)/\1/' | sed 's/^ //'`

if test "$PINSPOT_OS_NAME" = "OpenBSD"; then
    echo "check..."
    getent passwd $NAME
    if test $? -eq 0; then
	echo "already done"
	exit 0
    fi

    echo "exec..."
    if test -n "$UID" -a -n "$GID"; then
	useradd -u $UID -g $GID -m $NAME
	if test $? -ne 0; then exit 1; fi
    elif test -n "$UID"; then
	useradd -u $UID -m $NAME
	if test $? -ne 0; then exit 1; fi
    elif test -n "$GID"; then
	useradd -g $GID -m $NAME
	if test $? -ne 0; then exit 1; fi
    else
	useradd -m $NAME
	if test $? -ne 0; then exit 1; fi
    fi
    if test -n "$COMMENT"; then usermod -c "$COMMENT" $NAME; fi
    if test $? -ne 0; then exit 1; fi
    if test -n "$PASSWORD"; then usermod -p "$PASSWORD" $NAME; fi
    if test $? -ne 0; then exit 1; fi
    if test -n "$SHELL"; then usermod -s "$SHELL" $NAME; fi
    if test $? -ne 0; then exit 1; fi
    if test -n "$CLASS"; then usermod -L "$CLASS" $NAME; fi
    if test $? -ne 0; then exit 1; fi

    su -s /bin/sh $NAME -c "ssh-keygen -t rsa -N '' -C '' -f ~$NAME/.ssh/id_rsa"
    if test $? -ne 0; then exit 1; fi

    echo "result..."
    getent passwd $NAME
fi

