#!/bin/sh

# name: ...
# gid: ...

echo "$0"

NAME=`grep '^name:' $PINSPOT_ACTION_FILE | sed 's/^[^:]*:\(.*\)/\1/' | sed 's/^ //'`
if test -z "$NAME"; then
    echo "error: name missing"
    exit 1
fi
GID=`grep '^gid:' $PINSPOT_ACTION_FILE | sed 's/^[^:]*:\(.*\)/\1/' | sed 's/^ //'`

if test "$PINSPOT_OS_NAME" = "OpenBSD"; then
    echo "check..."
    groupinfo -e $NAME
    if test $? -eq 0; then
	echo "already done"
	exit 0
    fi

    echo "exec..."
    groupadd $NAME
    if test $? -ne 0; then exit 1; fi
    if test -n "$GID"; then groupmod -g $GID $NAME; fi
    if test $? -ne 0; then exit 1; fi

    echo "result..."
    getent group $NAME
fi
