#!/bin/sh

echo "$0"

FILE=/etc/ssh/sshd_config
TMP_FILE=$FILE.pinspot_tmp

echo "check..."
grep '^PasswordAuthentication no$' $FILE
if test $? -eq 0; then
    echo "already done"
    exit 0
fi

echo "exec..."
sed -e 's/^#\(PasswordAuthentication\).*$/\1 no/' $FILE > $TMP_FILE
cat $TMP_FILE > $FILE
rm $TMP_FILE

echo "result..."
grep '^PasswordAuthentication no$' $FILE
if test $? -ne 0; then
    echo "error"
    exit 1
fi

echo "restart sshd"
if test "$PINSPOT_OS_NAME" = "OpenBSD"; then
    kill -HUP `cat /var/run/sshd.pid`
fi
